---
php_packages:
  - php5-curl
  - php5-gd
  - php5-dev
  - php-pear

apache_modules:
  - expires
  - headers
  - rewrite
  - vhost_alias

apache_vhosts:
  - 000-local
  - 001-staging
  - 002-branch
  - 003-production
